### ISSUE TITLE
Error Compile Linux

### ISSUE THREAD

**Issue by azzahrah** [dengxiayehu/fqrtmpplayer#4]
make[2]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/crypto/ocsp'
ocsp.h => ../../include/openssl/ocsp.h
make[2]: Leaving directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/crypto/ocsp'
making links in crypto/ui...
make[2]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/crypto/ui'
ui.h => ../../include/openssl/ui.h
ui_compat.h => ../../include/openssl/ui_compat.h
make[2]: Leaving directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/crypto/ui'
making links in crypto/krb5...
make[2]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/crypto/krb5'
krb5_asn.h => ../../include/openssl/krb5_asn.h
make[2]: Leaving directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/crypto/krb5'
making links in crypto/cms...
make[2]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/crypto/cms'
cms.h => ../../include/openssl/cms.h
make[2]: Leaving directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/crypto/cms'
making links in crypto/pqueue...
make[2]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/crypto/pqueue'
pqueue.h => ../../include/openssl/pqueue.h
make[2]: Leaving directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/crypto/pqueue'
making links in crypto/ts...
make[2]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/crypto/ts'
ts.h => ../../include/openssl/ts.h
make[2]: Leaving directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/crypto/ts'
making links in crypto/srp...
make[2]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/crypto/srp'
srp.h => ../../include/openssl/srp.h
srptest.c => ../../test/srptest.c
make[2]: Leaving directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/crypto/srp'
making links in crypto/cmac...
make[2]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/crypto/cmac'
cmac.h => ../../include/openssl/cmac.h
make[2]: Leaving directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/crypto/cmac'
make[1]: Leaving directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/crypto'
making links in ssl...
make[1]: Entering directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/ssl'
ssl.h => ../include/openssl/ssl.h
ssl2.h => ../include/openssl/ssl2.h
ssl3.h => ../include/openssl/ssl3.h
ssl23.h => ../include/openssl/ssl23.h
tls1.h => ../include/openssl/tls1.h
dtls1.h => ../include/openssl/dtls1.h
kssl.h => ../include/openssl/kssl.h
srtp.h => ../include/openssl/srtp.h
ssltest.c => ../test/ssltest.c
heartbeat_test.c => ../test/heartbeat_test.c
clienthellotest.c => ../test/clienthellotest.c
sslv2conftest.c => ../test/sslv2conftest.c
make[1]: Leaving directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/ssl'
making links in engines...
make[1]: Entering directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/engines'
making links in engines/ccgost...
make[2]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/engines/ccgost'
make[2]: Nothing to be done for`links'.
make[2]: Leaving directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/engines/ccgost'
make[1]: Leaving directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/engines'
making links in apps...
make[1]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/apps'
make[1]: Nothing to be done for`links'.
make[1]: Leaving directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/apps'
making links in test...
make[1]: Entering directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/test'
make[1]: Nothing to be done for `links'.
make[1]: Leaving directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/test'
making links in tools...
make[1]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/tools'
make[1]: Nothing to be done for`links'.
make[1]: Leaving directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/tools'
generating dummy tests (if needed)...
make[1]: Entering directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/test'
md2test.c => dummytest.c
rc5test.c => dummytest.c
jpaketest.c => dummytest.c
make[1]: Leaving directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/test'

Configured for android-armv7.

**\* Because of configuration changes, you MUST do the following before
**\* building:

```
    make depend
```

making depend in crypto...
make[1]: Entering directory `/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-l                                                                                       inux-androideabi/openssl-1.0.2g/crypto'
../util/domd: 26: ../util/domd: arm-linux-androideabi-gcc: not found
make[1]: *** [local_depend] Error 1
make[1]: Leaving directory`/home/rtmpplayer/fqrtmpplayer/contrib/contrib-arm-li                                                                                       nux-androideabi/openssl-1.0.2g/crypto'
make: **\* [depend] Error 1
compile openssl-1.0.2g.tar.gz failed
Android NDK: ERROR:jni/Android.mk:rtmp: LOCAL_SRC_FILES points to a missing file  
Android NDK: Check that jni/../../contrib/install/lib/librtmp.so exists  or that                                                                                        its path is correct
/home/android/android-ndk-r12b/build/core/prebuilt-library.mk:45: **\* Android ND                                                                                       K: Aborting    .  Stop.
Buildfile: /home/rtmpplayer/fqrtmpplayer/player-android/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.4.1
 [checkenv] Installed at /home/android/android-sdk-linux

-setup:
     [echo] Project Name: FQRtmpPlayer
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 24.0.1
     [echo] Resolving Build Target for FQRtmpPlayer...

BUILD FAILED
/home/android/android-sdk-linux/tools/ant/build.xml:538: Unable to resolve proje                                                                                       ct target 'android-23'

**Comment by dengxiayehu** [comment]
Please install android sdk with target 23.
